version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: nest_task_db
      POSTGRES_USER: ganiyuomotayo
      POSTGRES_PASSWORD: omotayo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: